# Generated by Django 3.1.2 on 2020-10-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_lat',
            field=models.DecimalField(decimal_places=18, default='1000.00', max_digits=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_lng',
            field=models.DecimalField(decimal_places=18, default='1000.00', max_digits=25),
        ),
    ]
